### PR TITLE
Enhancement: Normalize composer.json

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] normalizes `composer.json`

💁‍♂️ I ran

```
$ composer global require localheinz/composer-normalize
```

followed by

```
$ composer normalize
```

For reference, see https://github.com/localheinz/composer-normalize.

### CODE REVIEW

**Comment by localheinz** [comment]
@jcchavezs 

Can do! Perhaps similar to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3542?

**Comment by jcchavezs** [comment]
I was thinking that this library is not changing composer.json too much so maybe it is overkill to check the composer.json on CI. Merging as it is.

**Comment by jcchavezs** [comment]
@localheinz would you mind to rebase?

**Comment by localheinz** [comment]
@jcchavezs 

Rebased!

**Pull request merged**
